import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<>
			<Head>
				<title>HPortfolio</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex h-screen min-h-screen w-screen">
				<div className="h-full w-[30%] flex-col bg-slate-900 max-sm:hidden md:block"></div>
				<div className="flex h-full w-full flex-col bg-slate-800 drop-shadow-2xl">
					<div className="flex h-32 w-full flex-row items-center justify-center text-center">
						<span className="text-5xl font-bold text-slate-300 drop-shadow-lg">
							Hamza Nasab
						</span>
					</div>
					<div className="flex h-full w-full flex-row">
						<div className="flex h-64 w-full flex-row">
							<div className="h-64 w-full flex-col bg-slate-700 p-2 transition ease-in-out hover:bg-slate-600 hover:drop-shadow-lg">
								A
							</div>
							<div className="h-64 w-full flex-col bg-slate-700 p-2 transition ease-in-out hover:bg-slate-600 hover:drop-shadow-lg">
								A
							</div>
						</div>
					</div>
				</div>
				<div className="h-full w-[30%] flex-col bg-slate-900 max-sm:hidden md:block"></div>
			</main>
		</>
	);
}
